

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."audio_tracks" (
    "id" bigint NOT NULL,
    "song_id" bigint NOT NULL,
    "title" "text" NOT NULL,
    "audio_file_url" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "color_key" "text",
    "order" integer,
    "peaks" "jsonb"
);


ALTER TABLE "public"."audio_tracks" OWNER TO "postgres";


ALTER TABLE "public"."audio_tracks" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."audio_tracks_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."collections" (
    "id" bigint NOT NULL,
    "slug" "text" NOT NULL,
    "title" "text" NOT NULL,
    "main_color" "text",
    "track_colors" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "artwork_file_url" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."collections" OWNER TO "postgres";


ALTER TABLE "public"."collections" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."collections_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."songs" (
    "id" bigint NOT NULL,
    "collection_id" bigint NOT NULL,
    "title" "text" NOT NULL,
    "lyrics" "jsonb",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "slug" "text" NOT NULL,
    "visible" boolean DEFAULT false NOT NULL,
    "order" bigint
);


ALTER TABLE "public"."songs" OWNER TO "postgres";


ALTER TABLE "public"."songs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."songs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."user_collections" (
    "id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "collection_id" bigint NOT NULL,
    "role" "text" NOT NULL
);


ALTER TABLE "public"."user_collections" OWNER TO "postgres";


ALTER TABLE "public"."user_collections" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."user_collections_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."audio_tracks"
    ADD CONSTRAINT "audio_tracks_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."collections"
    ADD CONSTRAINT "collections_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."songs"
    ADD CONSTRAINT "songs_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."user_collections"
    ADD CONSTRAINT "user_collections_pkey" PRIMARY KEY ("id");



CREATE INDEX "audio_tracks_song_id_idx" ON "public"."audio_tracks" USING "btree" ("song_id");



CREATE INDEX "songs_collection_id_idx" ON "public"."songs" USING "btree" ("collection_id");



ALTER TABLE ONLY "public"."audio_tracks"
    ADD CONSTRAINT "audio_tracks_song_id_fkey" FOREIGN KEY ("song_id") REFERENCES "public"."songs"("id");



ALTER TABLE ONLY "public"."songs"
    ADD CONSTRAINT "songs_collection_id_fkey" FOREIGN KEY ("collection_id") REFERENCES "public"."collections"("id");



ALTER TABLE ONLY "public"."user_collections"
    ADD CONSTRAINT "user_collections_collection_id_fkey" FOREIGN KEY ("collection_id") REFERENCES "public"."collections"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."user_collections"
    ADD CONSTRAINT "user_collections_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE "public"."audio_tracks" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "authenticated users can insert audio_tracks into their collecti" ON "public"."audio_tracks" FOR INSERT TO "authenticated" WITH CHECK ((EXISTS ( SELECT 1
   FROM ("public"."user_collections" "c"
     JOIN "public"."songs" "s" ON (("c"."collection_id" = "s"."collection_id")))
  WHERE ((( SELECT "auth"."uid"() AS "uid") = "c"."user_id") AND ("audio_tracks"."song_id" = "s"."id") AND ("c"."role" = ANY (ARRAY['admin'::"text", 'editor'::"text"]))))));



CREATE POLICY "authenticated users can insert songs into their collections" ON "public"."songs" FOR INSERT TO "authenticated" WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."user_collections" "c"
  WHERE ((( SELECT "auth"."uid"() AS "uid") = "c"."user_id") AND ("songs"."collection_id" = "c"."collection_id") AND ("c"."role" = ANY (ARRAY['admin'::"text", 'editor'::"text"]))))));



CREATE POLICY "authenticated users can read audio_tracks from their collection" ON "public"."audio_tracks" FOR SELECT USING ((EXISTS ( SELECT 1
   FROM ("public"."user_collections" "c"
     JOIN "public"."songs" "s" ON (("c"."collection_id" = "s"."collection_id")))
  WHERE ((( SELECT "auth"."uid"() AS "uid") = "c"."user_id") AND ("audio_tracks"."song_id" = "s"."id")))));



CREATE POLICY "authenticated users can read from user_collections" ON "public"."user_collections" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "authenticated users can read songs from their collections" ON "public"."songs" FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."user_collections" "c"
  WHERE ((( SELECT "auth"."uid"() AS "uid") = "c"."user_id") AND ("songs"."collection_id" = "c"."collection_id")))));



CREATE POLICY "authenticated users can read their collections" ON "public"."collections" FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."user_collections" "c"
  WHERE ((( SELECT "auth"."uid"() AS "uid") = "c"."user_id") AND ("collections"."id" = "c"."collection_id")))));



CREATE POLICY "authenticated users can update audio_tracks to their collection" ON "public"."audio_tracks" FOR UPDATE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM ("public"."user_collections" "c"
     JOIN "public"."songs" "s" ON (("c"."collection_id" = "s"."collection_id")))
  WHERE ((( SELECT "auth"."uid"() AS "uid") = "c"."user_id") AND ("audio_tracks"."song_id" = "s"."id") AND ("c"."role" = ANY (ARRAY['admin'::"text", 'editor'::"text"])))))) WITH CHECK (true);



CREATE POLICY "authenticated users can update songs in their collections" ON "public"."songs" FOR UPDATE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."user_collections" "c"
  WHERE ((( SELECT "auth"."uid"() AS "uid") = "c"."user_id") AND ("songs"."collection_id" = "c"."collection_id") AND ("c"."role" = ANY (ARRAY['admin'::"text", 'editor'::"text"])))))) WITH CHECK (true);



ALTER TABLE "public"."collections" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."songs" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."user_collections" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."audio_tracks" TO "anon";
GRANT ALL ON TABLE "public"."audio_tracks" TO "authenticated";
GRANT ALL ON TABLE "public"."audio_tracks" TO "service_role";



GRANT ALL ON SEQUENCE "public"."audio_tracks_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."audio_tracks_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."audio_tracks_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."collections" TO "anon";
GRANT ALL ON TABLE "public"."collections" TO "authenticated";
GRANT ALL ON TABLE "public"."collections" TO "service_role";



GRANT ALL ON SEQUENCE "public"."collections_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."collections_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."collections_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."songs" TO "anon";
GRANT ALL ON TABLE "public"."songs" TO "authenticated";
GRANT ALL ON TABLE "public"."songs" TO "service_role";



GRANT ALL ON SEQUENCE "public"."songs_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."songs_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."songs_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."user_collections" TO "anon";
GRANT ALL ON TABLE "public"."user_collections" TO "authenticated";
GRANT ALL ON TABLE "public"."user_collections" TO "service_role";



GRANT ALL ON SEQUENCE "public"."user_collections_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."user_collections_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."user_collections_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























drop extension if exists "pg_net";


  create policy "authenticated users can upload to audio-files 1o4vxz4_0"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check ((bucket_id = 'audio-files'::text));



