/**
 * Centralized icon exports. Change the import source to swap icon libraries.
 * All components import from this file, never directly from icon packages.
 */

// ── Tabler ───────────────────────────────────────────────────────────────────
export {
  IconMenu2 as IconMenu,
  IconWorld as IconGlobe,
  IconChevronDown as IconChevronDown,
  IconSearch as IconSearch,
  IconPlayerPlayFilled as IconPlay,
  IconPlayerPauseFilled as IconPause,
  IconPlayerSkipBackFilled as IconSkipPrev,
  IconPlayerSkipForwardFilled as IconSkipNext,
  IconVolume as IconVolumeOn,
  IconVolumeOff as IconVolumeOff,
  IconMicrophone as IconMic,
  IconMusic as IconMusic,
  IconUser as IconUser,
  IconUserPlus as IconUserPlus,
  IconLogin as IconLogIn,
  IconLogout as IconLogOut,
  IconKey as IconKey,
  IconLock as IconLock,
  IconEdit as IconEdit,
  IconCopy as IconCopy,
  IconTrash as IconTrash,
  IconUpload as IconUpload,
  IconDeviceFloppy as IconSave,
  IconCheck as IconCheck,
  IconPlus as IconPlus,
  IconX as IconClose,
  IconRowInsertBottom as IconInsertAfter,
  IconRowInsertTop as IconInsertBefore,
  IconColumnInsertLeft as IconInsertLeft,
  IconColumnInsertRight as IconInsertRight,
  IconColumns as IconColumns,
  IconArrowBackUp as IconUndo,
  IconArrowForwardUp as IconRedo,
  IconPalette as IconPalette,
  IconPaintFilled as IconCopyProperties,
  IconMessage as IconComment,
  IconClock as IconTimestamp,
  IconPlaylistAdd as IconAddStanza,
  IconArrowsSplit as IconSplitStanza,
  IconArrowsMoveVertical as IconJoinStanza,
  IconBraces as IconCode,
  IconHash as IconHash,
  IconLink as IconLink,
  IconEye as IconVisible,
  IconSettings as IconSettings,
  IconHelp as IconHelp,
  IconRefresh as IconDiscard,
  IconBan as IconProhibited,
  IconArrowUp as IconMoveUp,
  IconArrowDown as IconMoveDown,
  IconCactus as IconEmpty
} from "@tabler/icons-vue";
